<template>
  <div class="menu">
    <img src="../../assets/logo.png" />
    <!-- div id="content">
      <div id="exercise">
        <h1 class="dictionary">The Vowels</h1>
        <div id="pd">
          <p class="rubric">Select the pictures to hear the words.</p>
          <audio id="wordplayer">
            <source
              id="audiooggsrc"
              src="https://elt.oup.com/elt/students/letsgo/picturedictionary/lg5e_lb1_cd1_03_c.ogg"
              type="audio/ogg"
            />
            <source
              id="audiomp3src"
              src="https://elt.oup.com/elt/students/letsgo/picturedictionary/lg5e_lb1_cd1_03_c.mp3?cc=global&amp;selLanguage=en"
              type="audio/mpeg"
            />
            <p id="audiofallback">
              Sorry! The audio may not play in this browser. Your browser may
              download the audio when you select the picture
            </p>
          </audio>
          <ul id="audiodictionary">
            <li>
              <a
                href="https://elt.oup.com/elt/students/letsgo/picturedictionary/lg5e_lb1_cd1_03_a.mp3?cc=global&amp;selLanguage=en"
                class="audioitem"
                ><img
                  src="https://elt.oup.com/elt/students/letsgo/picturedictionary/lg5e_lb1_l1_06_01.jpg"
                  alt="Andy"
                  width="200"
                  height="132"
                />Andy</a
              >
            </li>
            <li>
              <a
                href="https://elt.oup.com/elt/students/letsgo/picturedictionary/lg5e_lb1_cd1_03_c.mp3?cc=global&amp;selLanguage=en"
                class="audioitem"
                ><img
                  src="https://elt.oup.com/elt/students/letsgo/picturedictionary/lg5e_lb1_l1_06_03.jpg"
                  alt="alligator"
                  width="200"
                  height="132"
                />alligator</a
              >
            </li>
            <li>
              <a
                href="https://elt.oup.com/elt/students/letsgo/picturedictionary/lg5e_lb1_cd1_03_b.mp3?cc=global&amp;selLanguage=en"
                class="audioitem"
                ><img
                  src="https://elt.oup.com/elt/students/letsgo/picturedictionary/lg5e_lb1_l1_06_02.jpg"
                  alt="ant"
                  width="200"
                  height="132"
                />ant</a
              >
            </li>
            <li>
              <a
                href="https://elt.oup.com/elt/students/letsgo/picturedictionary/lg5e_lb1_cd1_03_d.mp3?cc=global&amp;selLanguage=en"
                class="audioitem"
                ><img
                  src="https://elt.oup.com/elt/students/letsgo/picturedictionary/lg5e_lb1_l1_06_04.jpg"
                  alt="apple"
                  width="200"
                  height="132"
                />apple</a
              >
            </li>
            <li>
              <a
                href="https://elt.oup.com/elt/students/letsgo/picturedictionary/lg5e_lb1_cd1_06_a.mp3?cc=global&amp;selLanguage=en"
                class="audioitem"
                ><img
                  src="https://elt.oup.com/elt/students/letsgo/picturedictionary/lg5e_lb1_l2_08_01.jpg"
                  alt="Eddie"
                  width="200"
                  height="132"
                />Eddie</a
              >
            </li>
            <li>
              <a
                href="https://elt.oup.com/elt/students/letsgo/picturedictionary/lg5e_lb1_cd1_06_c.mp3?cc=global&amp;selLanguage=en"
                class="audioitem"
                ><img
                  src="https://elt.oup.com/elt/students/letsgo/picturedictionary/lg5e_lb1_l2_08_03.jpg"
                  alt="egg"
                  width="200"
                  height="132"
                />egg</a
              >
            </li>
            <li>
              <a
                href="https://elt.oup.com/elt/students/letsgo/picturedictionary/lg5e_lb1_cd1_06_b.mp3?cc=global&amp;selLanguage=en"
                class="audioitem"
                ><img
                  src="https://elt.oup.com/elt/students/letsgo/picturedictionary/lg5e_lb1_l2_08_02.jpg"
                  alt="elbow"
                  width="200"
                  height="132"
                />elbow</a
              >
            </li>
            <li>
              <a
                href="https://elt.oup.com/elt/students/letsgo/picturedictionary/lg5e_lb1_cd1_06_d.mp3?cc=global&amp;selLanguage=en"
                class="audioitem"
                ><img
                  src="https://elt.oup.com/elt/students/letsgo/picturedictionary/lg5e_lb1_l2_08_04.jpg"
                  alt="elephant"
                  width="200"
                  height="132"
                />elephant</a
              >
            </li>
            <li>
              <a
                href="https://elt.oup.com/elt/students/letsgo/picturedictionary/lg5e_lb1_cd1_09_a.mp3?cc=global&amp;selLanguage=en"
                class="audioitem"
                ><img
                  src="https://elt.oup.com/elt/students/letsgo/picturedictionary/lg5e_lb1_l3_10_01.jpg"
                  alt="Isabel"
                  width="200"
                  height="132"
                />Isabel</a
              >
            </li>
            <li>
              <a
                href="https://elt.oup.com/elt/students/letsgo/picturedictionary/lg5e_lb1_cd1_09_c.mp3?cc=global&amp;selLanguage=en"
                class="audioitem"
                ><img
                  src="https://elt.oup.com/elt/students/letsgo/picturedictionary/lg5e_lb1_l3_10_03.jpg"
                  alt="igloo"
                  width="200"
                  height="132"
                />igloo</a
              >
            </li>
            <li>
              <a
                href="https://elt.oup.com/elt/students/letsgo/picturedictionary/lg5e_lb1_cd1_09_b.mp3?cc=global&amp;selLanguage=en"
                class="audioitem"
                ><img
                  src="https://elt.oup.com/elt/students/letsgo/picturedictionary/lg5e_lb1_l3_10_02.jpg"
                  alt="ink"
                  width="200"
                  height="132"
                />ink</a
              >
            </li>
            <li>
              <a
                href="https://elt.oup.com/elt/students/letsgo/picturedictionary/lg5e_lb1_cd1_09_d.mp3?cc=global&amp;selLanguage=en"
                class="audioitem"
                ><img
                  src="https://elt.oup.com/elt/students/letsgo/picturedictionary/lg5e_lb1_l3_10_04.jpg"
                  alt="insect"
                  width="200"
                  height="132"
                />insect</a
              >
            </li>
            <li>
              <a
                href="https://elt.oup.com/elt/students/letsgo/picturedictionary/lg5e_lb1_cd1_12_a.mp3?cc=global&amp;selLanguage=en"
                class="audioitem"
                ><img
                  src="https://elt.oup.com/elt/students/letsgo/picturedictionary/lg5e_lb1_l4_12_01.jpg"
                  alt="Oliver"
                  width="200"
                  height="132"
                />Oliver</a
              >
            </li>
            <li>
              <a
                href="https://elt.oup.com/elt/students/letsgo/picturedictionary/lg5e_lb1_cd1_12_b.mp3?cc=global&amp;selLanguage=en"
                class="audioitem"
                ><img
                  src="https://elt.oup.com/elt/students/letsgo/picturedictionary/lg5e_lb1_l4_12_02.jpg"
                  alt="octopus"
                  width="200"
                  height="132"
                />octopus</a
              >
            </li>
            <li>
              <a
                href="https://elt.oup.com/elt/students/letsgo/picturedictionary/lg5e_lb1_cd1_12_c.mp3?cc=global&amp;selLanguage=en"
                class="audioitem"
                ><img
                  src="https://elt.oup.com/elt/students/letsgo/picturedictionary/lg5e_lb1_l4_12_03.jpg"
                  alt="omelet"
                  width="200"
                  height="132"
                />omelet</a
              >
            </li>
            <li>
              <a
                href="https://elt.oup.com/elt/students/letsgo/picturedictionary/lg5e_lb1_cd1_12_d.mp3?cc=global&amp;selLanguage=en"
                class="audioitem"
                ><img
                  src="https://elt.oup.com/elt/students/letsgo/picturedictionary/lg5e_lb1_l4_12_04.jpg"
                  alt="ostrich"
                  width="200"
                  height="132"
                />ostrich</a
              >
            </li>
            <li>
              <a
                href="https://elt.oup.com/elt/students/letsgo/picturedictionary/lg5e_lb1_cd1_15_a.mp3?cc=global&amp;selLanguage=en"
                class="audioitem"
                ><img
                  src="https://elt.oup.com/elt/students/letsgo/picturedictionary/lg5e_lb1_l5_14_01.jpg"
                  alt="Uncle Jim"
                  width="200"
                  height="132"
                />Uncle Jim</a
              >
            </li>
            <li>
              <a
                href="https://elt.oup.com/elt/students/letsgo/picturedictionary/lg5e_lb1_cd1_15_b.mp3?cc=global&amp;selLanguage=en"
                class="audioitem"
                ><img
                  src="https://elt.oup.com/elt/students/letsgo/picturedictionary/lg5e_lb1_l5_14_02.jpg"
                  alt="umpire"
                  width="200"
                  height="132"
                />umpire</a
              >
            </li>
            <li>
              <a
                href="https://elt.oup.com/elt/students/letsgo/picturedictionary/lg5e_lb1_cd1_15_c.mp3?cc=global&amp;selLanguage=en"
                class="audioitem"
                ><img
                  src="https://elt.oup.com/elt/students/letsgo/picturedictionary/lg5e_lb1_l5_14_03.jpg"
                  alt="umbrella"
                  width="200"
                  height="132"
                />umbrella</a
              >
            </li>
            <li>
              <a
                href="https://elt.oup.com/elt/students/letsgo/picturedictionary/lg5e_lb1_cd1_15_d.mp3?cc=global&amp;selLanguage=en"
                class="audioitem"
                ><img
                  src="https://elt.oup.com/elt/students/letsgo/picturedictionary/lg5e_lb1_l5_14_04.jpg"
                  alt="upside down"
                  width="200"
                  height="132"
                />upside down</a
              >
            </li>
          </ul>
        </div>
      </div>
    </div> -->
  </div>
</template>

<script setup lang="ts"></script>

<style scoped>
  .menu {
    width: 30%;
    height: 100%;
    /* border-left: 1px solid #eee; */
  }
</style>
